"""empty message

Revision ID: 7519cbfff6f0
Revises: 91e66ff953bc
Create Date: 2024-04-28 19:39:20.611284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7519cbfff6f0'
down_revision = '91e66ff953bc'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint('email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("email", type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
